Repository wazuh/wazuh-splunk, pull requests merged in 2018-10, with the labels that each got.

#246 3.6 Cluster monitoring section
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/views/manager/manager-welcome.html
  SplunkAppForWazuh/appserver/static/views/manager/monitoring/monitoring.html
Labels: 3.6, enhancement, frontend

#247 3.6 AWS Integration
  SplunkAppForWazuh/appserver/static/views/overview/aws/aws.html
  SplunkAppForWazuh/appserver/static/views/overview/overview-welcome.html
Labels: 3.7, enhancement

#252 3.6 Osquery integration
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/views/overview/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/views/overview/overview-welcome.html
Labels: 3.7, enhancement, frontend

#255 3.6 Enhanced queries in new overview FIM dashboard
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/views/overview/overview-fim.html
  SplunkAppForWazuh/default/inputs.conf
Labels: 3.7, enhancement, frontend

#256 3.6 issue 250
  SplunkAppForWazuh/appserver/controllers/api.py
Labels: 3.7, backend, enhancement

#258 3.6 Fix #254
  SplunkAppForWazuh/appserver/static/js/services/filterService/filterService.js
Labels: 3.7, fixes, frontend

#259 3.6 Task #257
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewPolicyMonitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/get-ids/getIdService.js
  SplunkAppForWazuh/appserver/static/js/services/index.js
  SplunkAppForWazuh/appserver/static/views/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/views/agents/overview/overview.html
Labels: 3.7, enhancement

#261 3.7 New management section
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configurationCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-config-item/wz-config-item.css
  SplunkAppForWazuh/appserver/static/js/directives/wz-config-item/wz-config-item.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-config-item/wz-config-item.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-no-config/wz-no-config.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-no-config/wz-no-config.js
  SplunkAppForWazuh/appserver/static/js/services/xml-beautifier/xml-beautifier.js
  SplunkAppForWazuh/appserver/static/js/utils/config-handler.js
  SplunkAppForWazuh/appserver/static/js/utils/query-config.js
  SplunkAppForWazuh/appserver/static/js/utils/remove-hash-key.js
  SplunkAppForWazuh/appserver/static/views/agents/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/views/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
Labels: 3.7, enhancement, frontend, redesign

#262 Wazuh v3.6.1 - Splunk v7.1.3-rev16
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/loader.css
  SplunkAppForWazuh/appserver/static/css/thirdPartyStyles/material/animate.css
  SplunkAppForWazuh/appserver/static/css/thirdPartyStyles/material/material.css
  SplunkAppForWazuh/appserver/static/css/thirdPartyStyles/material/oxygen.css
  SplunkAppForWazuh/appserver/static/css/thirdPartyStyles/material/passion.css
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/libs/angular.js
  SplunkAppForWazuh/appserver/static/js/libs/animate.js
  SplunkAppForWazuh/appserver/static/js/libs/aria.js
  SplunkAppForWazuh/appserver/static/js/libs/material.js
  SplunkAppForWazuh/appserver/static/js/libs/messages.js
  SplunkAppForWazuh/appserver/static/js/libs/router.js
  SplunkAppForWazuh/appserver/static/js/main.js
  SplunkAppForWazuh/appserver/static/views/overview/aws/aws.html
  SplunkAppForWazuh/appserver/static/views/overview/overview-welcome.html
  SplunkAppForWazuh/default/data/ui/html/index.html
  SplunkAppForWazuh/default/package.conf
Labels: 3.6, release

#265 3.7 settings redesign
  SplunkAppForWazuh/appserver/static/views/settings/about.html
  SplunkAppForWazuh/appserver/static/views/settings/api.html
  SplunkAppForWazuh/appserver/static/views/settings/logs/logs.html
Labels: 3.7, frontend, redesign

#266 Avoid showing tables if any syscollector data is received
  SplunkAppForWazuh/appserver/static/views/agents/inventory/inventory.html
Labels: 3.7, enhancement

#267 3.7 check diff params update api
  SplunkAppForWazuh/appserver/controllers/manager.py
  package.json
  tests/index.js
Labels: 3.7, backend, enhancement

#270 3.7 Added is_sync information to configuration
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/views/agents/configuration/configuration.html
Labels: 3.7, enhancement, frontend

#271 Fix word break for groups list
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/views/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/views/agents/overview/overview.html
Labels: 3.7, frontend, redesign

#272 Several 3.7.0-7.2.0 testing bugfixes
  .eslintignore
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/utils/query-config.js
  SplunkAppForWazuh/appserver/static/views/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/views/overview/overview-welcome.html
  package.json
Labels: 3.7, fixes

#274 3.7.0 reported bug fixes
  SplunkAppForWazuh/appserver/static/js/controllers/settings/settingsApiCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
  SplunkAppForWazuh/appserver/static/views/agents/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/views/manager/monitoring/monitoring.html
  SplunkAppForWazuh/appserver/static/views/settings/api.html
  SplunkAppForWazuh/appserver/static/views/settings/logs/logs.html
Labels: 3.7, fixes

#277 3.7 reported bugfixes
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/views/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/views/overview/overview-vulnerabilities.html
Labels: 3.7, fixes

#281 Updating to new keys
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
  SplunkAppForWazuh/bin/get_agents_status.py
Labels: 3.7, fixes

#282 Several bugfixes for v3.7.0
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/views/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/views/manager/groups/groups.html
Labels: 3.7, fixes

#286 3.7 Table fixes and several grammar corrections
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
Labels: 3.7, fixes

#287 3.7 reported bugfixes
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/views/manager/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/views/manager/manager-ruleset.html
  SplunkAppForWazuh/appserver/static/views/settings/index.html
Labels: 3.7, fixes

#289 3.7 decoders chip fix
  SplunkAppForWazuh/appserver/static/views/manager/manager-decoders.html
Labels: 3.7, fixes

#291 3.7 cluster status
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/statusCtrl.js
  SplunkAppForWazuh/appserver/static/views/manager/status/status.html
Labels: 3.7, enhancement

#292 Updated changelog
  CHANGELOG.md
Labels: 3.7, enhancement

#279 3.7 Add prettier script to package.json
  package.json
Labels: 3.7, enhancement

#299 Cluster multi-node logs
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/app.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/managerLogsCtrl.js
  SplunkAppForWazuh/appserver/static/js/filters/index.js
  SplunkAppForWazuh/appserver/static/js/filters/module.js
  SplunkAppForWazuh/appserver/static/js/filters/order-object/order-object.js
  SplunkAppForWazuh/appserver/static/views/manager/manager-logs.html
Labels: 3.7, enhancement, frontend

#301 Aborted promises in wz-table
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-welcome-card/wz-welcome-card.html
Labels: 3.7, fixes

#302 Changing node filter to node_name in agent list
  SplunkAppForWazuh/appserver/static/views/agents/agents/agents.html
Labels: 3.7, fixes

#303 Bump revision
  CHANGELOG.md
  package.json
Labels: 3.7

#304 Refactor Overview Vulnerabilities
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overviewAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overviewFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/policy-monitoring/overviewPolicyMonitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overview-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overviewOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overview-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overviewVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/token-model/urlTokenModelService.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/chart/area-chart.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/chart/bar-chart.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/chart/column-chart.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/chart/linear-chart.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/chart/pie-chart.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/inputs/dropdown-input.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/inputs/time-picker.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/search/search-handler.js
Labels: 3.7, backend, enhancement

#306 Refactor overview
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overviewFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/gdpr/overview-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/gdpr/overviewGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overview-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/overviewPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/pci/overview-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/pci/overviewPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overview-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overviewOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/inputs/dropdown-input.js
Labels: 3.7, enhancement, refactor

#305 Fixed sections in configuration on demand
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
Labels: 3.7, fixes

#319 Refactor management ruleset
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/dev-tools.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/ruleset.js
Labels: 3.7, refactor

#322 Fixed typos and reported changes
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-no-config/wz-no-config.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/views/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/views/overview/overview-welcome.html
Labels: 3.7, enhancement

#318 Agent cluster node selector
  SplunkAppForWazuh/appserver/static/js/config/routes.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/views/agents/agents/agents.html
  package.json
Labels: 3.7, enhancement

#321 Refactor agents section
  SplunkAppForWazuh/appserver/static/js/config/index.js
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agents-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agentsAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agents-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agentsGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agents-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agentsPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agentsPolicyMonitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agents-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agentsOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/pci/overviewPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/search/search-handler.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/table/table.js
Labels: 3.7, enhancement, refactor

#327 Hiding XML tags
  SplunkAppForWazuh/appserver/static/views/manager/configuration/configuration.html
Labels: fixes
