Repository wazuh/wazuh-splunk, pull requests merged in 2018-12, with the labels that each got.

#391 Fixed dynamic filters
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agents-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agentsAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agents-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agentsCiscatCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agents-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agentsGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agents-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agentsPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agentsPolicyMonitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agentsOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agents-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agentsVirusTotalCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overviewAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/ciscat/ciscatCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overviewFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overview-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overviewOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js
Labels: 3.7, fixes

#393 Refactor of the table directive
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/check-gap.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/click-action.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/data.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/init.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/listeners.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/pagination.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/parse-value.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/rows.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/sort.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/js/libs/babel.js
  SplunkAppForWazuh/appserver/static/js/libs/es6.js
  SplunkAppForWazuh/appserver/static/js/utils/filter-handler.js
Labels: 3.8, frontend, refactor

#395 3.8 Action column for agents table
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/click-action.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
Labels: 3.8, enhancement

#400 3.8 New feature: Dynamic tables fed by arrays instead of API
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-data-table/wz-data-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-data-table/wz-data-table.js
Labels: 3.8, enhancement, frontend

#399 3.8 New feature: AWS-like filter bar
  SplunkAppForWazuh/appserver/static/css/styles/loader.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/data.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/listeners.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.css
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
Labels: 3.8, enhancement, frontend

#409 Fix 'and' operator in API requests
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
Labels: 3.8, backend, enhancement

#419 Applied string format methods
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
Labels: 3.8, fixes

#378 Showing/Hiding syscheck files in overview agents
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
Labels: 3.8

#396 Added services and syscheck files for windows and linux agents
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
Labels: 3.8, enhancement

#420 3.8 Implemented mutex in DB backend
  SplunkAppForWazuh/bin/db.py
  SplunkAppForWazuh/bin/log.py
Labels: 3.8, fixes, operations

#423 Bump version
  CHANGELOG.md
  README.md
  SplunkAppForWazuh/default/app.conf
  SplunkAppForWazuh/default/package.conf
  package.json
Labels: 3.7, release

#392 Fixed cluster node filter in managerLogsCtrl
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/managerLogsCtrl.js
Labels: 3.8, backend, enhancement

#411 3.8 requested changes
  SplunkAppForWazuh/appserver/static/css/images/osquery.png
  SplunkAppForWazuh/appserver/static/css/images/osquery.svg
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/settingsApiCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-welcome-card/wz-welcome-card.html
  SplunkAppForWazuh/appserver/static/js/services/dataService/dataService.js
  SplunkAppForWazuh/appserver/static/js/utils/config-handler.js
Labels: 3.8, bug

#424 3.8 reporting
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overview-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/reporting/reportingService.js
  SplunkAppForWazuh/appserver/static/js/services/vis2png/vis2png.js
Labels: 3.8, enhancement

#410 3.8 tooltips typos
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/api.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
  SplunkAppForWazuh/appserver/static/js/services/date-diff/dateDiffService.js
  SplunkAppForWazuh/appserver/static/js/services/index.js
Labels: 3.8, fixes

#427 3.8 Fixed unhandled error with trim() method
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
Labels: 3.8, fixes, frontend

#432 3.8 New features: XML editor for configurations and agents selector
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/loader.css
  SplunkAppForWazuh/appserver/static/css/styles/wz-multiple-selector.css
  SplunkAppForWazuh/appserver/static/css/styles/xml-editor.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/reporting/reportingCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/logs/logsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-multiple-selector/wz-multiple-selector.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-multiple-selector/wz-multiple-selector.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: 3.8, enhancement

#434 3.8 UX improvements and fixes
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/dev-tools.html
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: 3.8, enhancement

#436 3.8 Fix monitoring index schema
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
  SplunkAppForWazuh/bin/get_agents_status.py
Labels: 3.8, backend

#437 3.8 AWS updated searches
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
Labels: 3.8
