Repository wazuh/wazuh-splunk, pull requests merged in 2018-11, with the labels that each got.

#328 Refactor settings
  SplunkAppForWazuh/appserver/static/js/controllers/overview/gdpr/overviewGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/index/settingsIndexCtrl.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/inputs/dropdown-input.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/inputs/time-picker.js
  SplunkAppForWazuh/appserver/static/js/services/visualizations/viz/viz.js
Labels: 3.7, enhancement, refactor

#329 Agents controlles to classes
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agentsAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agentsGdprCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agentsPolicyMonitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agentsOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
Labels: 3.7, enhancement, refactor

#333 Improve agent status history
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
  SplunkAppForWazuh/bin/get_agents_status.py
  SplunkAppForWazuh/default/inputs.conf
Labels: enhancement, frontend, refactor

#335 Fix log initialization
  SplunkAppForWazuh/bin/db.py
Labels: 3.6, fixes

#336 v3.6.1-7.1.3-log-fix
  SplunkAppForWazuh/bin/db.py
Labels: 3.6, fixes

#337 3.7 Syscollector tables
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agentsPciCtrl.js
Labels: 3.7, enhancement, frontend

#340 3.7 virustotal
  SplunkAppForWazuh/appserver/static/css/images/app_saved_objects.svg
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agents-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agentsVirusTotalCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/virustotal/overview-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/virustotal/overviewVirusTotalCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
Labels: 3.7, enhancement, frontend

#343 Handling non-existent user ID
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
Labels: 3.7, fixes

#296 3.7 improve backend rules
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
  SplunkAppForWazuh/appserver/static/js/services/splunkStoreService/splunkStoreService.js
  tests/external_files/jsonOfuscatedResponses.js
  tests/manager.js
  tests/ofuscate.js
Labels: 3.7, backend, enhancement

#344 Revert "3.7 improve backend rules"
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
  SplunkAppForWazuh/appserver/static/js/services/splunkStoreService/splunkStoreService.js
  tests/external_files/jsonOfuscatedResponses.js
  tests/manager.js
  tests/ofuscate.js
Labels: 3.7, bug

#346 Added group bar to Agents > Configuration
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configuration.html
Labels: 3.7, enhancement

#348 3.7 New feature: export dynamic tables in CSV format
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/manager-logs.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/managerLogsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/ruleset.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/logs/logsCtrl.js
  SplunkAppForWazuh/appserver/static/js/libs/file-saver/file-saver.js
  SplunkAppForWazuh/appserver/static/js/main.js
  SplunkAppForWazuh/appserver/static/js/services/csv-request/csvRequestService.js
  SplunkAppForWazuh/appserver/static/js/services/index.js
Labels: 3.7, backend, enhancement

#342 3.7 Added CIS-CAT Integration
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agents-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agentsCiscatCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overviewAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/ciscat/ciscatCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/ciscat/overview-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
Labels: 3.7, enhancement

#330 Splunk extensions
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overviewWelcomeCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/extensions/extensions.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/extensions/extensionsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/main/settings.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/main/settingsCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js
  SplunkAppForWazuh/appserver/static/js/services/currentDataService/currentDataService.js
  SplunkAppForWazuh/default/config.conf
Labels: 3.7, backend, enhancement

#331 Discover button
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/discover/discover.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
Labels: 3.7, enhancement, frontend

#364 Bump Splunk version (v7.2.1)
  CHANGELOG.md
  README.md
  SplunkAppForWazuh/default/app.conf
  SplunkAppForWazuh/default/package.conf
  package.json
Labels: 3.7, release

#361 3.7 issue 350(Agents status monitoring doesn't draw timeline properly)
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
  SplunkAppForWazuh/default/inputs.conf
Labels: 3.7, backend, fixes

#362 3.7 implement tooltips
  SplunkAppForWazuh/appserver/static/css/styles/component.css
  SplunkAppForWazuh/appserver/static/css/styles/loader.css
  SplunkAppForWazuh/appserver/static/css/styles/wazuh_decorations.css
  SplunkAppForWazuh/appserver/static/css/styles/wz_tooltips.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoring.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/api.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
Labels: 3.7, frontend, hotfixes

#357 3.7 Added table with syscheck monitored files of an agent
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
Labels: 3.7, enhancement

#365 Solved secondary states without ng-click(select(...)), fixes #338
  SplunkAppForWazuh/appserver/static/js/run/run.js
Labels: 3.7, bug, enhancement

#373 3.7 admin mode
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
Labels: 3.7, backend

#359 3.7 Added local ports column to syscollector table
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.js
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
Labels: 3.7, enhancement

#355 3.7 Solved clean keys errors
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
  SplunkAppForWazuh/appserver/static/js/services/splunkStoreService/splunkStoreService.js
Labels: 3.7, backend, bug

#363 3.7 Modularized configuration view and enabling XML visualization files
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/active-response/active-response.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/active-response/agents-active-response.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/agentless/agentless.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/alerts/alerts.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/amazon-s3/amazon-s3.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/both-configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/cis-cat/cis-cat.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/client-buffer/client-buffer.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/client/client.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/cluster/cluster.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configurationCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/database-output/database-output.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/global-configuration/global-configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/integrations/integrations.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/integrity-monitoring/integrity-monitoring.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/log-collection/log-collection.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/open-scap/open-scap.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/policy-monitoring/policy-monitoring.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/registration-service/registration-service.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/ruleset/ruleset.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/syscollector/syscollector.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/vulnerabilities/vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/wazuh-commands/wazuh-commands.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/welcome/welcome.html
  SplunkAppForWazuh/appserver/static/js/libs/json2xml/jsontoxml.js
  SplunkAppForWazuh/appserver/static/js/main.js
  SplunkAppForWazuh/appserver/static/js/services/xml-beautifier/xml-beautifier.js
  SplunkAppForWazuh/appserver/static/js/utils/config-handler.js
Labels: 3.7, enhancement, frontend

#374 Fixed bad transition on agents
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
Labels: 3.7, fixes, frontend

#372 3.7 bad align overview
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
Labels: 3.7

#367 3.7 fixed extensions
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/services/currentDataService/currentDataService.js
Labels: 3.7, enhancement, fixes

#380 3.7 Improved error handler in ui.router states
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agents-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/both-configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/manager-logs.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/managerLogsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/ruleset.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overviewOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overviewVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/logs/logsCtrl.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/default/config.conf
Labels: 3.7, enhancement, fixes
