Repository wazuh/wazuh-splunk, pull requests merged in 2019-06, with the labels that each got.

#731 Adapt DevTools
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
Labels: enhancement, fixes

#741 Fix duplicated text box in Management > logs
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/manager-logs.html
Labels: fixes, frontend

#722 Sort properly
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration-assessment/agents-ca.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
  SplunkAppForWazuh/appserver/static/js/services/dataService/dataService.js
Labels: UI/UX, enhancement, frontend

#727 Interactive guide to add agents
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/wazuh_decorations.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-register-agent/wz-register-agent.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-register-agent/wz-register-agent.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-svg/wz-svg.html
Labels: design, enhancement, frontend

#737 Fix admin mode
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
Labels: fixes

#750 3.10 several fixes
  SplunkAppForWazuh/appserver/static/css/styles/component.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/run/run.js
Labels: fixes, frontend

#743 Fix agent bar
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
Labels: fixes

#766 Fixes after testing v3.9.3-7.3.0-rc2
  SplunkAppForWazuh/appserver/static/js/controllers/agents/docker/agents-docker.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/settingsApiCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/date-diff/dateDiffService.js
Labels: bug

#745 Fix Agents > Inventory
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-data-table/wz-data-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
Labels: fixes, frontend

#771 Prepare 3.9.3 release
  CHANGELOG.md
  SplunkAppForWazuh/default/package.conf
  package.json
Labels: release
