Repository wazuh/wazuh-splunk, pull requests merged in 2019-02, with the labels that each got.

#529 3.9 discover sub tab
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agents-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agents-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agents-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agents-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agents-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agents-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/discover/discover.html
  SplunkAppForWazuh/appserver/static/js/controllers/discover/discoverCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overview-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/aws.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/ciscat/overview-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overview-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/gdpr/overview-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overview-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/pci/overview-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/policy-monitoring/overview-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overview-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/virustotal/overview-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overview-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-bar/wz-bar.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-bar/wz-bar.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-discover/wz-discover.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-discover/wz-discover.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/js/services/currentDataService/currentDataService.js
  SplunkAppForWazuh/appserver/static/js/services/filterService/filterService.js
Labels: 3.9, enhancement

#531 Fix run.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
Labels: fixes, hotfixes

#532 3.9 fix local edition
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/editRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/manager-edit-rulesets.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/editionCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: 3.9

#534 Edit cluster nodes config
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/editionCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
  SplunkAppForWazuh/appserver/static/js/services/file-editor/file-editor.js
Labels: 3.9, enhancement

#535 3.9 restart nodes
  SplunkAppForWazuh/appserver/static/css/styles/layout.css
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs-mg.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/navTabCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/editRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
  SplunkAppForWazuh/appserver/static/js/services/index.js
  SplunkAppForWazuh/appserver/static/js/services/restartService/restartService.js
Labels: 3.9

#538 Updated autocomplete list
  SplunkAppForWazuh/appserver/controllers/api.py
Labels: 3.9

#537 Store the API database into Splunk
  CHANGELOG.md
  README.md
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/overview-states.js
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/managerLogsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/ruleset.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/api.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/settingsApiCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/extensions/extensionsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/appserver/static/js/services/api-manager/apiMgrService.js
  SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js
  SplunkAppForWazuh/appserver/static/js/services/currentDataService/currentDataService.js
  SplunkAppForWazuh/appserver/static/js/services/requestService/requestService.js
  SplunkAppForWazuh/appserver/static/js/services/splunkStoreService/splunkStoreService.js
  SplunkAppForWazuh/bin/db.py
  SplunkAppForWazuh/bin/tinydb/__init__.py
  SplunkAppForWazuh/bin/tinydb/database.py
  SplunkAppForWazuh/bin/tinydb/middlewares.py
  SplunkAppForWazuh/bin/tinydb/operations.py
  SplunkAppForWazuh/bin/tinydb/queries.py
  SplunkAppForWazuh/bin/tinydb/storages.py
  SplunkAppForWazuh/bin/tinydb/utils.py
  SplunkAppForWazuh/bin/tinydb/version.py
  SplunkAppForWazuh/default/app.conf
  SplunkAppForWazuh/default/collections.conf
  SplunkAppForWazuh/default/package.conf
  SplunkAppForWazuh/default/transforms.conf
  package.json
  tests/manager.js
Labels: 3.9

#545 3.9 improve restart
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs-mg.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/navTabCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/editRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
  SplunkAppForWazuh/appserver/static/js/services/restartService/restartService.js
Labels: 3.9

#546 Fix extensions toggle
  SplunkAppForWazuh/appserver/static/js/controllers/settings/extensions/extensionsCtrl.js
Labels: fixes

#548 Fix polling agents state
  SplunkAppForWazuh/bin/db.py
  SplunkAppForWazuh/bin/get_agents_status.py
Labels: backend, bug, fixes

#556 Restart agent from the App
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
Labels: enhancement

#558 Fix runjs
  SplunkAppForWazuh/appserver/static/js/run/run.js
Labels: fixes, frontend

#559 Fix downloading API response in Devtools
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/dev-tools.html
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
Labels: fixes

#561 Ruleset edition refactor
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs-mg.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/navTabCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configurationCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/welcome/welcome.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/editionCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/status.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/statusCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/extensions/extensionsCtrl.js
Labels: refactor

#563 Confirm restart
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs-mg.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/navTabCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/status.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/statusCtrl.js
Labels: enhancement

#564 Fixes on editing cluster configuration
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/both-configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configurationCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/editionCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/status.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/welcome/manager-welcome.html
  SplunkAppForWazuh/appserver/static/js/services/restartService/restartService.js
Labels: fixes

#568 Ui enhancements
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/editRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/manager-edit-rulesets.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/editionCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/index.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/status.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
  SplunkAppForWazuh/appserver/static/js/services/file-editor/file-editor.js
  SplunkAppForWazuh/appserver/static/js/services/restartService/restartService.js
Labels: enhancement

#572 File edition changes
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/xml-editor.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration-assessment/agents-ca.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/both-configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs-mg.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/edit-configuration/manager-edit-groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/edition.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/edition/editionCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/ruleset.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/status.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-multiple-selector/wz-multiple-selector.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
  SplunkAppForWazuh/appserver/static/js/services/file-editor/file-editor.js
Labels: enhancement

#576 Changes and fixes in groups
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
Labels: enhancement

#573 Add delay of 15 seconds to cluster restart function
  SplunkAppForWazuh/appserver/static/js/services/restartService/restartService.js
Labels: enhancement

#578 Permit special charsets in API credentials
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/services/api-manager/apiMgrService.js
Labels: bug, fixes

#582 Bump version
  CHANGELOG.md
  SplunkAppForWazuh/default/package.conf
Labels: release
