Repository wazuh/wazuh-splunk, pull requests merged in 2019-01, with the labels that each got.

#442 Implemented mutex fix in get db methods
  SplunkAppForWazuh/bin/db.py
Labels: 3.8, fixes

#444 3.8 Audit keys for configuration (whodata)
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/integrity-monitoring/integrity-monitoring.html
Labels: 3.8

#445 Disabled several extensions by default
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/default/config.conf
Labels: 3.8, backend

#452 3.8 New network addresses syscollector table
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
Labels: 3.8, enhancement

#455 3.8 Bugfixes
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/component.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/integrity-monitoring/integrity-monitoring.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/monitoring/monitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-multiple-selector/wz-multiple-selector.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
  SplunkAppForWazuh/appserver/static/js/libs/codemirror-conv/formatting.js
  SplunkAppForWazuh/appserver/static/js/services/group-handler/group-handler.js
  SplunkAppForWazuh/bin/get_agents_status.py
  package.json
Labels: 3.8, fixes

#459 3.8 Bugfixes
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/css/styles/wz-multiple-selector.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agentsAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agentsCiscatCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agentsPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agentsOpenScapCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/policy-monitoring/overview-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/index/settingsIndexCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-multiple-selector/wz-multiple-selector.html
  SplunkAppForWazuh/appserver/static/js/run/run.js
  package.json
Labels: 3.8, fixes

#461 3.8 Added full API response to DevTools
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agents-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agents-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agents-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agents-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agents-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agents-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overview-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/aws.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/ciscat/overview-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overview-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/gdpr/overview-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overview-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/pci/overview-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/policy-monitoring/overview-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overview-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/virustotal/overview-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overview-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overviewVulnerabilitiesCtrl.js
  package.json
Labels: 3.8, enhancement

#463 3.8 bugfixes
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/click-action.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  package.json
Labels: 3.8, fixes

#466 Undo discover rule.id
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/lib/click-action.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
Labels: 3.8

#468 3.8 reporting inventory
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/config/routes/agents-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.html
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
  SplunkAppForWazuh/appserver/static/js/services/reporting/reportingService.js
  package.json
Labels: 3.8, enhancement

#469 3.8 UX Changes in groups configuration editor
  SplunkAppForWazuh/appserver/static/css/styles/wazuh_decorations.css
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
Labels: 3.8

#475 Fix wazuh logo on low resolution
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
Labels: 3.8, enhancement

#477 Showing up rule details if they're an object
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
  package.json
Labels: 3.8

#478 3.8 UI changes for editing groups
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/height.css
  SplunkAppForWazuh/appserver/static/css/styles/typography.css
  SplunkAppForWazuh/appserver/static/js/config/routes/management-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agentsGeneralCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventoryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agentsPciCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/awsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osqueryCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.js
  SplunkAppForWazuh/appserver/static/js/run/run.js
  SplunkAppForWazuh/appserver/static/js/services/group-handler/group-handler.js
  SplunkAppForWazuh/appserver/static/js/services/rawTableData/rawTableDataService.js
  SplunkAppForWazuh/appserver/static/js/services/reporting/reportingService.js
  package.json
Labels: 3.8

#485 Fixed several typos
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/amazon-s3/amazon-s3.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/manager-logs.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
Labels: 3.9, fixes

#487 Customized empty results message in tables directive
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/static/appIconAlt.png
  SplunkAppForWazuh/static/appLogo.png
Labels: 3.9, enhancement

#498 3.9 fix reporting
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/js/controllers/agents/audit/agents-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agents-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/gdpr/agents-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/general/agents-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/inventory/inventory.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/pcidss/agents-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/policy-monitoring/agents-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/scap/agents-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/virustotal/agents-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overview-audit.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/aws/aws.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/ciscat/overview-ciscat.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overview-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/gdpr/overview-gdpr.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overview-general.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/pci/overview-pci.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/policy-monitoring/overview-pm.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/scap/overview-openscap.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/virustotal/overview-virustotal.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overview-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/services/reporting/reportingService.js
  SplunkAppForWazuh/appserver/static/js/services/vis2png/vis2png.js
Labels: 3.9, fixes

#496 Escape not allowed characters
  SplunkAppForWazuh/appserver/static/js/directives/wz-xml-file-editor/wz-xml-file-editor.js
Labels: 3.9, bug

#503 DevTools improvements
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/dev-tools.html
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
Labels: 3.9

#499 New configuration viewer directive
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/active-response/active-response.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/active-response/agents-active-response.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/agentless/agentless.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/alerts/alerts.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/cis-cat/cis-cat.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/client-buffer/client-buffer.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/client/client.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/cluster/cluster.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/database-output/database-output.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/global-configuration/global-configuration.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/log-collection/log-collection.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/osquery/osquery.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/policy-monitoring/policy-monitoring.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/registration-service/registration-service.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/ruleset/ruleset.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/syscollector/syscollector.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/wazuh-commands/wazuh-commands.html
  SplunkAppForWazuh/appserver/static/js/directives/index.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-config-viewer/wz-config-viewer.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-config-viewer/wz-config-viewer.js
  SplunkAppForWazuh/appserver/static/js/utils/config-handler.js
Labels: 3.9

#507 Allowing the same query multiple times for Dev Tools
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
Labels: 3.9, fixes

#516 Avoid to send the first request in DevTools
  SplunkAppForWazuh/appserver/static/js/controllers/dev-tools/devToolsCtrl.js
Labels: enhancement

#517 3.9 show chip fim
  SplunkAppForWazuh/appserver/static/js/controllers/agents/ciscat/agentsCiscatCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/audit/overviewAuditCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/fim/overviewFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/policy-monitoring/overviewPolicyMonitoringCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overviewVulnerabilitiesCtrl.js
  SplunkAppForWazuh/appserver/static/js/services/filterService/filterService.js
Labels: 3.9, enhancement

#518 New agents header
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/agentsOverviewCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
Labels: enhancement

#519 Added an option to edit the group configuration from the groups table
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table-directive.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
Labels: enhancement, frontend
