Repository wazuh/wazuh-splunk, pull requests merged in 2022-01, with the labels that each got.

#1141 fix(1096)-changes on onresize function
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/directives/wz-table-server-side/wz-table-server-side-directive.js
Labels: 4.3

#1138 Fix on save rules or decoders files
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetIdCtrl.js
Labels: 4.3

#1137 Agent's name overflows in agent overview
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
Labels: 4.3

#1186 Rebranding 1185
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/appserver/static/css/images/docker.svg
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/logo.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_blue_full.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_blue_iso.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_blue_iso_big.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_blue_logo.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_white_full.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_white_full_edge.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_white_iso.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_white_iso_big.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_white_iso_edge.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/png/wazuh_white_logo.png
  SplunkAppForWazuh/appserver/static/css/images/wazuh/svg/wazuh_white_full.svg
  SplunkAppForWazuh/appserver/static/css/images/wazuh/svg/wazuh_white_iso.svg
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/default/data/ui/nav/default.xml
  SplunkAppForWazuh/static/appIcon.png
  SplunkAppForWazuh/static/appIconAlt.png
  SplunkAppForWazuh/static/appIconAlt_2x.png
  SplunkAppForWazuh/static/appIcon_2x.png
  SplunkAppForWazuh/static/appLogo.png
  SplunkAppForWazuh/static/appLogo_2x.png
  SplunkOverview.png
Labels: 4.3

#1146 Added persistence from within a cluster
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/controllers/queue.py
  SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js
  SplunkAppForWazuh/appserver/static/js/services/currentDataService/currentDataService.js
  SplunkAppForWazuh/bin/check_queue.py
  SplunkAppForWazuh/bin/db.py
  SplunkAppForWazuh/bin/get_agents_status.py
  SplunkAppForWazuh/default/collections.conf
Labels: 4.3

#1172 Updated deprecated authd options
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/registration-service/registration-service.html
  SplunkAppForWazuh/bin/api_info/endpoints.json
  SplunkAppForWazuh/bin/api_info/security-actions.json
Labels: 4.3

#1166 Added API alias value to registered APIs
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/api.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/settingsApiCtrl.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
  SplunkAppForWazuh/appserver/static/js/services/notificationService/notificationService.js
  SplunkAppForWazuh/bin/db.py
  SplunkAppForWazuh/default/collections.conf
  SplunkAppForWazuh/default/transforms.conf
Labels: 4.3

#1182 Add the configured timeout to the API's requests
  SplunkAppForWazuh/bin/wazuh_api.py
  SplunkAppForWazuh/bin/wazuhtoken.py
Labels: bug, 4.3

#1217 Add margin-top to security options
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/security/main/security.html
Labels: 4.3

#1224 fix(security_service.js): console log removed
  SplunkAppForWazuh/appserver/static/js/services/security_services/security_service.js
Labels: 4.3

#1216 Read only create new agent
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
Labels: 4.3

#1223 Added condition for destroy
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
Labels: 4.3

#1215 Agent count are not centered
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
Labels: 4.3

#1229 Hide the Agents Status bar based on permissions
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overviewWelcomeCtrl.js
Labels: 4.3, found:4.3-8.2.2

#1230 Role check added in setting>configuration
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/config/routes/settings-states.js
  SplunkAppForWazuh/appserver/static/js/controllers/settings/configuration/settingsConfigCtrl.js
Labels: 4.3

#1232 Agent status chart data disappear
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
Labels: 4.3
