Repository wazuh/wazuh-splunk, pull requests merged in 2022-05, with the labels that each got.

#1318 RBAC management configuration permissions prompt
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/breadcrumbs/breadcrumbs.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/configurationCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/welcome/welcome.html
Labels: 4.3

#1320 [UI][Agents] Fixed the appearance of a toast message related to the forwarder when there is no data of agents and the agent deployment guide is displayed
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
Labels: bug, UI/UX

#1322 Add powershell version warning
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/component.css
  SplunkAppForWazuh/appserver/static/js/directives/wz-register-agent/wz-register-agent.html
Labels: enhancement
