Repository wazuh/wazuh-splunk, pull requests merged in 2022-02, with the labels that each got.

#1236 Rebranding Wazuh colors setup
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/component.css
  SplunkAppForWazuh/appserver/static/css/styles/kbn.css
  SplunkAppForWazuh/appserver/static/css/styles/layout.css
  SplunkAppForWazuh/appserver/static/css/styles/typography.css
  SplunkAppForWazuh/appserver/static/css/styles/variables.css
  SplunkAppForWazuh/appserver/static/css/styles/wazuh_decorations.css
  SplunkAppForWazuh/appserver/static/css/styles/wz-add-filter-chip.css
  SplunkAppForWazuh/appserver/static/css/styles/xml-editor.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/overview/overview.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/api/api.html
  SplunkAppForWazuh/appserver/static/js/controllers/settings/configuration/configuration.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.css
  SplunkAppForWazuh/appserver/static/js/directives/wz-multiple-selector/wz-multiple-selector.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-register-agent/wz-register-agent.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-svg/wz-svg.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-svg/wz-svg.js
  SplunkAppForWazuh/appserver/static/js/directives/wz-table-server-side/wz-table-server-side.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-table/wz-table.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-tag-filter/wz-tag-filter.css
  SplunkAppForWazuh/static/appIcon.png
  SplunkAppForWazuh/static/appIcon_2x.png
Labels: 4.3

#1239 Fix `Key not found` error while loading extensions
  SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js
  SplunkAppForWazuh/appserver/static/js/services/currentDataService/currentDataService.js
Labels: 4.3

#1237 Add function get inputs.conf
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
Labels: 4.3

#1262 Fix filter on the daemons logs
  SplunkAppForWazuh/appserver/static/js/controllers/management/logs/managerLogsCtrl.js
Labels: 4.3

#1260 Fix non-sortable columns on the Security section tables
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/security/roles-mapping/rolesMapping.html
  SplunkAppForWazuh/appserver/static/js/controllers/security/roles/roles.html
  SplunkAppForWazuh/appserver/static/js/controllers/security/users/users.html
  SplunkAppForWazuh/appserver/static/js/services/key-equivalence/keyEquivalenceService.js
Labels: 4.3

#1258 Fix sorting on the Groups table
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
Labels: 4.3

#1257 Fixed endpoint dir and template filename
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/managerDecodersCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/managerRulesetCtrl.js
Labels: 4.3

#1243 Quicksettings dialog show api alias
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.js
Labels: 4.3

#1244 Changed `Overview Security` agent status evolution spantime to 1m
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/overview/general/overviewGeneralCtrl.js
Labels: 4.3

#1266 Fix import CDB list file
  CHANGELOG.md
  SplunkAppForWazuh/appserver/controllers/api.py
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/static/js/directives/wz-upload-files/wz-upload-files.js
  SplunkAppForWazuh/bin/wazuh_api.py
Labels: 4.3

#1261 CDB list input validation
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/manager-cdb.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/cdb/managerCdbIdCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/decoders/manager-decoders.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset-id.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/rules/manager-ruleset.html
  SplunkAppForWazuh/appserver/static/js/services/cdb-editor/cdb-editor.js
Labels: 4.3

#1256 Validate new groups name on the UI
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
Labels: bug, 4.3

#1270 Reload triggers for custom conf files.
  SplunkAppForWazuh/default/app.conf
Labels: enhancement, community

#1279 Visualizations init on html wrapper load
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agents-fim.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/fim/agentsFimCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agents-vulnerabilities.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/vulnerabilities/agentsVulnerabilitiesCtrl.js
Labels: 4.3

#1282 Removed header menu fixed height
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/security/main/security.html
  SplunkAppForWazuh/appserver/static/js/directives/wz-menu/wz-menu.css
  SplunkAppForWazuh/default/config.conf
Labels: 4.3

#1283 Fix an error on the search string for the Overview Alerts Summary Table
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/overview/vulnerabilities/overviewVulnerabilitiesCtrl.js
Labels: 4.3
