Repository wazuh/wazuh-splunk, pull requests merged in 2022-06, with the labels that each got.

#1276 Added conditional disable to apply button
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groups.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/groups/groupsCtrl.js
Labels: UI/UX

#1294 Fix outdated documentation links
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/js/controllers/agents/configuration/agentConfigCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/azure-logs/azure-logs.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/cluster/cluster.html
  SplunkAppForWazuh/appserver/static/js/controllers/security/roles-mapping/rolesMapping.html
  SplunkAppForWazuh/appserver/static/js/controllers/security/roles-mapping/rolesMappingCtrl.js
Labels: 4.3.5

#1292 Add pending status to Agents
  CHANGELOG.md
  SplunkAppForWazuh/appserver/static/css/styles/common.css
  SplunkAppForWazuh/appserver/static/css/styles/variables.css
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agents.html
  SplunkAppForWazuh/appserver/static/js/controllers/agents/agents/agentsCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/status.html
  SplunkAppForWazuh/appserver/static/js/controllers/management/status/statusCtrl.js
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overview-welcome.html
  SplunkAppForWazuh/appserver/static/js/controllers/overview/welcome/overviewWelcomeCtrl.js
Labels: enhancement

#1340 Fix 'Unexpected Wazuh version' error
  SplunkAppForWazuh/appserver/controllers/manager.py
  SplunkAppForWazuh/appserver/controllers/report.py
  SplunkAppForWazuh/bin/log.py
  SplunkAppForWazuh/bin/utils/config.py
Labels: bug
